const pricingData = {
  monthly: {
    basicIndex: {
      subscriptionId: 'basic_index_option_monthly_001',
      price: 8000,
      features: {
        researchCalls: '10-14 Index Option Calls/Week',
        algo: 'Nifty & Sensex Options',
        brokerAccounts: '1 Broker Account',
        telegram: 'Whatsapp Alerts',
        strategies: '2 Strategy',
        whatsapp: 'Whatsapp and Call Support',
      },
    },
    moderateIndex: {
      subscriptionId: 'moderate_index_option_monthly_002',
      price: 17000,
      features: {
        researchCalls: '35-45 Calls in a Week',
        algo: '4-5 Index Option & 10 Stock (NIFTY/BANK-NIFTY/SENSEX/MIDCAP/ 10 STOCK OPTIONS)',
        brokerAccounts: '3 Broker Accounts',
        strategies: '4 Strategies',
        marketReport: 'Monthly Article & Report',
        telegram: 'Whatsapp Alerts',
        callSupport: 'Whatsapp and Call Support',
      },
    },
    advanceIndex: {
      subscriptionId: 'advance_index_option_monthly_003',
      price: 34000,
      features: {
        researchCalls: '90-110 Weekly Calls',
        algo: '4-5 Index, Stocks & Mcx ( All Segments )',
        brokerAccounts: '8 Broker Accounts',
        strategies: '6-25 Strategies',
        marketReport: 'Weekly Articles, Reports, market ideas etc',
        telegram: 'Whatsapp Alerts',
        callSupport: 'Whatsapp and Call Support, Mail / Other Support',
      },
    },
    stockOption: {
      subscriptionId: 'stock_option_monthly_004',
      price: 15000,
      features: {
        researchCalls: '10+ Stock Option Calls/Week',
        algo: 'Stock Option Strategy Algo',
        brokerAccounts: '2 Broker Accounts',
        riskManagement: 'Stop-Loss & Target Tracking',
        telegram: 'Telegram & WhatsApp Updates',
      },
    },
    stockFuture: {
      subscriptionId: 'stock_future_monthly_005',
      price: 25000,
      features: {
        researchCalls: '15+ Stock Future Calls/Week',
        algo: 'Stock Future Trend Algo',
        brokerAccounts: '3 Broker Accounts',
        portfolio: 'Mini Portfolio Assistance',
        smaAlerts: 'SMA + Volatility Alerts',
        callSupport: 'Call Support (Market Hours)',
      },
    },
    equityResearch: {
      subscriptionId: 'equity_research_monthly_006',
      price: 11000,
      features: {
        researchCalls: '5–8 Equity Research Reports/Month',
        algo: 'Basic Fundamental Scanner',
        marketInsights: 'Weekly Market Summary',
        telegram: 'Telegram Channel Access',
        whatsapp: 'Direct Analyst Q&A (WhatsApp)',
      },
    },
    longTermEquity: {
      subscriptionId: 'long_term_equity_research_monthly_007',
      price: 5000,
      features: {
        researchCalls: '2–3 Long-Term Picks/Month',
        algo: 'Long-Term Trend Detection Model',
        reports: 'Quarterly Sectoral Reports',
        newsletter: 'Monthly Investor Newsletter',
        support: 'Email Support Only',
      },
    },
    mcx: {
      subscriptionId: 'mcx_monthly_008',
      price: 25000,
      features: {
        researchCalls: 'Options/Futures',
        names: 'Bullion, Energy & Copper',
        algo: '6-25+ MCX Options/Futures Calls/Week',
        reports: 'MCX Options/Futures Algo',
        newsletter: '5 Broker Accounts',
        stopLoss: '3-5 Strategies',
        newsLetter: 'Monthly Article & Report',
        support: 'Whatsapp / Telegram Premium / Call',
      },
    },
  },

  quarterly: {
    basicIndex: {
      subscriptionId: 'basic_index_option_quarterly_001',
      price: 16000,
      features: {
        researchCalls: '10-14 Index Option Calls/Week',
        algo: 'Nifty & Sensex Options',
        brokerAccounts: '1 Broker Account',
        telegram: 'Whatsapp Alerts',
        strategies: '2 Strategy',
        whatsapp: 'Whatsapp and Call Support',
      },
    },
    moderateIndex: {
      subscriptionId: 'moderate_index_option_quarterly_002',
      price: 40000,
      features: {
        researchCalls: '35-45 Calls in a Week',
        algo: '4-5 Index Option & 10 Stock (NIFTY/BANK-NIFTY/SENSEX/MIDCAP/ 10 STOCK OPTIONS)',
        brokerAccounts: '3 Broker Accounts',
        strategies: '4 Strategies',
        marketReport: 'Monthly Article & Report',
        telegram: 'Whatsapp Alerts',
        callSupport: 'Whatsapp and Call Support',
      },
    },
    advanceIndex: {
      subscriptionId: 'advance_index_option_quarterly_003',
      price: 80000,
      features: {
        researchCalls: '90-110 Weekly Calls',
        algo: '4-5 Index, Stocks & Mcx ( All Segments )',
        brokerAccounts: '8 Broker Accounts',
        strategies: '6-25 Strategies',
        marketReport: 'Weekly Articles, Reports, market ideas etc',
        telegram: 'Whatsapp Alerts',
        callSupport: 'Whatsapp and Call Support, Mail / Other Support',
      },
    },
    stockOption: {
      subscriptionId: 'stock_option_quarterly_004',
      price: 40000,
      features: {
        researchCalls: '10+ Stock Option Calls/Week',
        algo: 'Stock Option Strategy Algo',
        brokerAccounts: '2 Broker Accounts',
        riskManagement: 'Stop-Loss & Target Tracking',
        telegram: 'Telegram & WhatsApp Updates',
      },
    },
    stockFuture: {
      subscriptionId: 'stock_future_quarterly_005',
      price: 65000,
      features: {
        researchCalls: '15+ Stock Future Calls/Week',
        algo: 'Stock Future Trend Algo',
        brokerAccounts: '3 Broker Accounts',
        portfolio: 'Mini Portfolio Assistance',
        smaAlerts: 'SMA + Volatility Alerts',
        callSupport: 'Call Support (Market Hours)',
      },
    },
    equityResearch: {
      subscriptionId: 'equity_research_quarterly_006',
      price: 28000,
      features: {
        researchCalls: '5–8 Equity Research Reports/Month',
        algo: 'Basic Fundamental Scanner',
        marketInsights: 'Weekly Market Summary',
        telegram: 'Telegram Channel Access',
        whatsapp: 'Direct Analyst Q&A (WhatsApp)',
      },
    },
    longTermEquity: {
      subscriptionId: 'long_term_equity_research_quarterly_007',
      price: 13000,
      features: {
        researchCalls: '2–3 Long-Term Picks/Month',
        algo: 'Long-Term Trend Detection Model',
        reports: 'Quarterly Sectoral Reports',
        newsletter: 'Monthly Investor Newsletter',
        support: 'Email Support Only',
      },
    },
    mcx: {
      subscriptionId: 'mcx_quarterly_008',
      price: 65000,
      features: {
        researchCalls: 'Options/Futures',
        names: 'Bullion, Energy & Copper',
        algo: '6-25+ MCX Options/Futures Calls/Week',
        reports: 'MCX Options/Futures Algo',
        newsletter: '5 Broker Accounts',
        stopLoss: '3-5 Strategies',
        newsLetter: 'Monthly Article & Report',
        support: 'Whatsapp / Telegram Premium / Call',
      },
    },
  },

  halfYearly: {
    basicIndex: {
      subscriptionId: 'basic_index_option_halfyearly_001',
      price: 30000,
      features: {
        researchCalls: '10-14 Index Option Calls/Week',
        algo: 'Nifty & Sensex Options',
        brokerAccounts: '1 Broker Account',
        telegram: 'Whatsapp Alerts',
        strategies: '2 Strategy',
        whatsapp: 'Whatsapp and Call Support',
      },
    },
    moderateIndex: {
      subscriptionId: 'moderate_index_option_halfyearly_002',
      price: 75000,
      features: {
        researchCalls: '35-45 Calls in a Week',
        algo: '4-5 Index Option & 10 Stock (NIFTY/BANK-NIFTY/SENSEX/MIDCAP/ 10 STOCK OPTIONS)',
        brokerAccounts: '3 Broker Accounts',
        strategies: '4 Strategies',
        marketReport: 'Monthly Article & Report',
        telegram: 'Whatsapp Alerts',
        callSupport: 'Whatsapp and Call Support',
      },
    },
    advanceIndex: {
      subscriptionId: 'advance_index_option_halfyearly_003',
      price: 125000,
      features: {
        researchCalls: '90-110 Weekly Calls',
        algo: '4-5 Index, Stocks & Mcx ( All Segments )',
        brokerAccounts: '8 Broker Accounts',
        strategies: '6-25 Strategies',
        marketReport: 'Weekly Articles, Reports, market ideas etc',
        telegram: 'Whatsapp Alerts',
        callSupport: 'Whatsapp and Call Support, Mail / Other Support',
      },
    },
    stockOption: {
      subscriptionId: 'stock_option_halfyearly_004',
      price: 75000,
      features: {
        researchCalls: '10+ Stock Option Calls/Week',
        algo: 'Stock Option Strategy Algo',
        brokerAccounts: '2 Broker Accounts',
        riskManagement: 'Stop-Loss & Target Tracking',
        telegram: 'Telegram & WhatsApp Updates',
      },
    },
    stockFuture: {
      subscriptionId: 'stock_future_halfyearly_005',
      price: 120000,
      features: {
        researchCalls: '15+ Stock Future Calls/Week',
        algo: 'Stock Future Trend Algo',
        brokerAccounts: '3 Broker Accounts',
        portfolio: 'Mini Portfolio Assistance',
        smaAlerts: 'SMA + Volatility Alerts',
        callSupport: 'Call Support (Market Hours)',
      },
    },
    equityResearch: {
      subscriptionId: 'equity_research_halfyearly_006',
      price: 52000,
      features: {
        researchCalls: '5–8 Equity Research Reports/Month',
        algo: 'Basic Fundamental Scanner',
        marketInsights: 'Weekly Market Summary',
        telegram: 'Telegram Channel Access',
        whatsapp: 'Direct Analyst Q&A (WhatsApp)',
      },
    },
    longTermEquity: {
      subscriptionId: 'long_term_equity_research_halfyearly_007',
      price: 23000,
      features: {
        researchCalls: '2–3 Long-Term Picks/Month',
        algo: 'Long-Term Trend Detection Model',
        reports: 'Quarterly Sectoral Reports',
        newsletter: 'Monthly Investor Newsletter',
        support: 'Email Support Only',
      },
    },
    mcx: {
      subscriptionId: 'mcx_halfyearly_008',
      price: 100000,
      features: {
        researchCalls: 'Options/Futures',
        names: 'Bullion, Energy & Copper',
        algo: '6-25+ MCX Options/Futures Calls/Week',
        reports: 'MCX Options/Futures Algo',
        newsletter: '5 Broker Accounts',
        stopLoss: '3-5 Strategies',
        newsLetter: 'Monthly Article & Report',
        support: 'Whatsapp / Telegram Premium / Call',
      },
    },
  },
};

export default pricingData;
