import Footer from "@/components/Footer";
import FormComp from "@/components/FormComp/FormComp";
import Header1 from "@/components/Header1";
import LoadGoogleAdsIframe from "@/components/LoadGoogleAdsIframe";
import LoadGoogleAdsScript from "@/components/LoadGoogleAdsScript";
import React from "react";

const Page = () => {
  return (
    <>
      <LoadGoogleAdsScript />
      <LoadGoogleAdsIframe />
      <Header1 />
      <div className="pt-[80px] pb-[30px]">
        <h1 className="w-full bg-[#aee9e7] flex justify-center items-center h-[35vh] text-[#102b5c] font-[999] text-[5vh] xl:text-[8vh]">
          Disclaimer
        </h1>
        <div className="px-[5%] xl:px-[25%]">
          <h2 className="text-left text-[6vh] font-bold text-black   pt-[30px]">
            Disclaimer
          </h2>
          <div className="text-lg">
            <li className="text-left text-[#555555]  p1 pt-[30px] font-medium ">
              All subscription fees paid to Brain Auto Tech is not refundable.
              We do not provide trading tips nor are we investment adviser.
            </li>
            <li className="text-left text-[#555555]   p1  font-medium  pt-[5px]">
              {" "}
              Our service is solely restricted to automated trading application
              development, deployment and maintenance.
            </li>
            <div className="text-left text-[#555555]  p1 pt-[30px] font-medium ">
              <li className="">
                All algorithms are based on backtested data but we do not
                provide any guarantee for their performance in future.
              </li>
              <li className="pt-[5px]">
                {" "}
                The algorithm running in automated system is agreed with user
                prior deployment and we do not take any liability for any loss
                generated by the same.
              </li>
              <li className="pt-[5px] ">
                Past performance of advise/strategy/model does not indicate the
                future performance of any current or future strategy/model or
                advise by Brain Auto Tech Trades and actual returns may differ
                significantly from that depicted herein due to various factors
                including but not limited to impact costs, expense charged,
                timing of entry/exit, timing of additional flows/redemptions,
                individual client mandates, specific portfolio construction
                characteristics etc.
              </li>
              <li className="pt-[5px]">
                {" "}
                There is no assurance or guarantee that the objectives of any
                strategy/model.
              </li>
            </div>
          </div>
        </div>
      </div>
      <FormComp />
      <hr className="pb-[20px]"></hr>
      <Footer />
    </>
  );
};

export default Page;
