services:
  # server:
  #   build:
  #     context: ./
  #     dockerfile: dockerfile
  #   ports:
  #     - "9000:9000"
  #   depends_on:
  #     - db
  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - "8002:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: blueline@gmail.com
  # #     PGADMIN_DEFAULT_PASSWORD: 12345
  # swagger:
  #   build:
  #     context: ./
  #     dockerfile: dockerfile.swagger
  #   ports:
  #     - "9999:8080"
  #   volumes:
  #     - ../docs:/docs
  db:
    build:
      context: ./
      dockerfile: dockerfile.pg
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  # cache:
  #   build:
  #     context: ./
  #     dockerfile: dockerfile.redis
  #   ports:
  #     - "6379:6379"
      # - "8001:8001"
    # volumes:
    #   - cache-data:/data

volumes:
  db-data:
