const pricingData = {
  monthly: {
    subscriptionId: "pre-monthly",
    price: 1000,
    features: {
      charts: 2,
      indicators: 5,
      historicalBars: "10K",
      connections: 10,
      priceAlerts: 20,
      technicalAlerts: 20,
      watchlistAlerts: 0,
      ads: false,
      volumeProfile: true,
      customTimeframes: true,
      customRangeBars: true,
      multipleWatchlists: true,
      barReplay: true,
      indicatorsOnIndicators: true,
      chartDataExport: false,
      intradayCharts: false,
      customFormulas: false,
      timePriceOpportunity: false,
      volumeFootprint: false,
      volumeCandles: false,
      autoChartPatterns: false,
      nonExpiringAlerts: false,
      publishingScripts: false,
      secondBasedIntervals: false,
      tickBasedIntervals: false,
      professionalMarketData: false,
      prioritySupport: false,
    },
  },
  quarterly: {
    subscriptionId: "pre-quarterly",
    price: 2400,
    features: {
      charts: 4,
      indicators: 10,
      historicalBars: "10K",
      connections: 20,
      priceAlerts: 100,
      technicalAlerts: 100,
      watchlistAlerts: 0,
      ads: false,
      volumeProfile: true,
      customTimeframes: true,
      customRangeBars: true,
      multipleWatchlists: true,
      barReplay: true,
      indicatorsOnIndicators: true,
      chartDataExport: true,
      intradayCharts: true,
      customFormulas: true,
      timePriceOpportunity: false,
      volumeFootprint: false,
      volumeCandles: false,
      autoChartPatterns: false,
      nonExpiringAlerts: false,
      publishingScripts: false,
      secondBasedIntervals: false,
      tickBasedIntervals: false,
      professionalMarketData: false,
      prioritySupport: false,
    },
  },
  halfyearly: {
    subscriptionId: "pre-half-yearly",
    price: 3840,
    features: {
      charts: 8,
      indicators: 25,
      historicalBars: "20K",
      connections: 50,
      priceAlerts: 400,
      technicalAlerts: 400,
      watchlistAlerts: 2,
      ads: false,
      volumeProfile: true,
      customTimeframes: true,
      customRangeBars: true,
      multipleWatchlists: true,
      barReplay: true,
      indicatorsOnIndicators: true,
      chartDataExport: true,
      intradayCharts: true,
      customFormulas: true,
      timePriceOpportunity: true,
      volumeFootprint: true,
      volumeCandles: true,
      autoChartPatterns: true,
      nonExpiringAlerts: false,
      publishingScripts: false,
      secondBasedIntervals: false,
      tickBasedIntervals: false,
      professionalMarketData: false,
      prioritySupport: false,
    },
  },
};

export default pricingData;
